DROP TABLE IF EXISTS `user`;
CREATE TABLE `user`(
  `id` INT (11) PRIMARY KEY NOT NULL ,
  `name` VARCHAR(255) NOT NULL UNIQUE,
  `pwd` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255),
  `avatar` VARCHAR(255) DEFAULT '/',
  `date` VARCHAR(255)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `user`
  MODIFY `id` INT(11) AUTO_INCREMENT,AUTO_INCREMENT=1;